//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaGlobal_BugTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public int bugID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_found { get; set; }
        public string found_on_branch { get; set; }
        public string found_by { get; set; }
        public string status { get; set; }
        public int Employee_employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
